# --- !Ups
ALTER TABLE accessibility ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE accessibility RENAME ebean_timestamp TO object_version;
ALTER TABLE accessibility ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE answer ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE answer RENAME ebean_timestamp TO object_version;
ALTER TABLE answer ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE attachment ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE attachment RENAME ebean_timestamp TO object_version;
ALTER TABLE attachment ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE comment ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE comment RENAME ebean_timestamp TO object_version;
ALTER TABLE comment ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE default_working_hours ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE default_working_hours RENAME ebean_timestamp TO object_version;
ALTER TABLE default_working_hours ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exception_working_hours ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exception_working_hours RENAME ebean_timestamp TO object_version;
ALTER TABLE exception_working_hours ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE course ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE course RENAME ebean_timestamp TO object_version;
ALTER TABLE course ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam RENAME ebean_timestamp TO object_version;
ALTER TABLE exam ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_enrolment ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_enrolment RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_enrolment ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_inspection ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_inspection RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_inspection ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_machine ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_machine RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_machine ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_participation ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_participation RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_participation ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_record ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_record RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_record ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_room ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_room RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_room ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_score ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_score RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_score ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_section ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_section RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_section ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_starting_hour ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_starting_hour RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_starting_hour ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE exam_type ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE exam_type RENAME ebean_timestamp TO object_version;
ALTER TABLE exam_type ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE general_settings ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE general_settings RENAME ebean_timestamp TO object_version;
ALTER TABLE general_settings ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE language ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE language RENAME ebean_timestamp TO object_version;
ALTER TABLE language ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE mail_address ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE mail_address RENAME ebean_timestamp TO object_version;
ALTER TABLE mail_address ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE multiple_choise_option ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE multiple_choise_option RENAME ebean_timestamp TO object_version;
ALTER TABLE multiple_choise_option ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE organisation ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE organisation RENAME ebean_timestamp TO object_version;
ALTER TABLE organisation ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE question ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE question RENAME ebean_timestamp TO object_version;
ALTER TABLE question ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE reservation ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE reservation RENAME ebean_timestamp TO object_version;
ALTER TABLE reservation ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE "role" ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE "role" RENAME ebean_timestamp TO object_version;
ALTER TABLE "role" ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE software ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE software RENAME ebean_timestamp TO object_version;
ALTER TABLE software ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE app_user ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE app_user RENAME ebean_timestamp TO object_version;
ALTER TABLE app_user ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE tag ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE tag RENAME ebean_timestamp TO object_version;
ALTER TABLE tag ALTER object_version TYPE BIGINT USING 1;
ALTER TABLE user_language ALTER ebean_timestamp DROP DEFAULT;
ALTER TABLE user_language RENAME ebean_timestamp TO object_version;
ALTER TABLE user_language ALTER object_version TYPE BIGINT USING 1;

# --- !Downs
-- No going back
