os: linux

dist: xenial

language:
  - scala

jdk:
  - openjdk11

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE USER sitnet WITH PASSWORD 'sitnetsitnet';" -U postgres
  - psql -c 'CREATE DATABASE sitnet_test WITH OWNER 'sitnet';' -U postgres
  - sed -i 's/\/var\/log\/exam/logs/g' $TRAVIS_BUILD_DIR/conf/logback.xml
  - npm i -g npm@latest
  - nvm install 16
  - rm -rf ui/node_modules
  - cd ui
  - npm install
script:
  - npm run build
  - cd ..
  - sbt test

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
