dist: trusty

sudo: false

language:
  - scala

jdk:
  - oraclejdk8

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE USER sitnet WITH PASSWORD 'sitnetsitnet';" -U postgres
  - psql -c 'CREATE DATABASE sitnet_test WITH OWNER 'sitnet';' -U postgres
  - sed -i 's/\/var\/log\/exam/logs/g' $TRAVIS_BUILD_DIR/conf/logback.xml
  - nvm install 8.9.1
  - nvm use 8.9.1

script:
  - npm install
  - sbt package
  - sbt test


before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $TRAVIS_BUILD_DIR/node_modules

