before_script:
  - psql -c "CREATE USER sitnet WITH PASSWORD 'sitnetsitnet';" -U postgres
  - psql -c 'CREATE DATABASE sitnet_test WITH OWNER 'sitnet';' -U postgres
  - sudo mkdir -p /var/log/exam
  - sudo touch /var/log/exam/application.log
  - sudo chmod a+w /var/log/exam/application.log
  - nvm install 8.9.1
  - nvm use 8.9.1

script:
  - npm install
  - sbt package
  - sbt test

services:
  - postgresql

addons:
  postgresql: "9.6"

language:
  - scala

jdk:
  - oraclejdk8
