######################################################################
#
# Production initial-data
#
# Halutessa tämän tiedoston tiedot voidaan ladata tietokantaan
# ensimmäisen käynnistyksen yhteydessä
#
# ks. Global.java
#
######################################################################


user-roles:
    - &role-admin !!models.Role
      name: ADMIN

    - &role-student !!models.Role
      name: STUDENT

    - &role-teacher !!models.Role
      name: TEACHER

######################################################################

user_languages:
    - &suomi !!models.UserLanguage
      nativeLanguageCode: fi
      nativeLanguageName: Suomi
      UILanguageCode: fi
      UILanguageName: Suomi

    - &englanti !!models.UserLanguage
      nativeLanguageCode: en
      nativeLanguageName: Englanti
      UILanguageCode: en
      UILanguageName: Englanti

    - &ruotsi !!models.UserLanguage
      nativeLanguageCode: sv
      nativeLanguageName: ruotsi
      UILanguageCode: sv
      UILanguageName: ruotsi

######################################################################

exam-types:

  - &partial !!models.ExamType
    type: PARTIAL

  - &final !!models.ExamType
    type: FINAL

################################################################

languages:

  - &fi !!models.Language
    code: fi
  - &sv !!models.Language
    code: sv
  - &en !!models.Language
    code: en
  - &de !!models.Language
    code: de

################################################################

grade-scales:

  - &zerotofive !!models.GradeScale
    description: ZERO_TO_FIVE

  - &latin !!models.GradeScale
    description: LATIN

  - &approvedrejected !!models.GradeScale
    description: APPROVED_REJECTED


grades:

  - !!models.Grade
    name: 0
    gradeScale: *zerotofive

  - !!models.Grade
    name: 1
    gradeScale: *zerotofive

  - !!models.Grade
    name: 2
    gradeScale: *zerotofive

  - !!models.Grade
    name: 3
    gradeScale: *zerotofive

  - !!models.Grade
    name: 4
    gradeScale: *zerotofive

  - !!models.Grade
    name: 5
    gradeScale: *zerotofive

  - !!models.Grade
    name: I
    gradeScale: *latin

  - !!models.Grade
      name: I
      gradeScale: *latin

  - !!models.Grade
      name: A
      gradeScale: *latin

  - !!models.Grade
      name: B
      gradeScale: *latin

  - !!models.Grade
      name: N
      gradeScale: *latin

  - !!models.Grade
      name: C
      gradeScale: *latin

  - !!models.Grade
      name: M
      gradeScale: *latin

  - !!models.Grade
      name: E
      gradeScale: *latin

  - !!models.Grade
      name: L
      gradeScale: *latin

  - !!models.Grade
    name: APPROVED
    gradeScale: *approvedrejected

  - !!models.Grade
    name: REJECTED
    gradeScale: *approvedrejected

################################################################

softwares:
  - &Matematica !!models.Software
    name: Matematica

  - &Firefox !!models.Software
    name: Firefox

  - &Excel !!models.Software
    name: Excel

  - &Mathcad !!models.Software
    name: Mathcad

  - &Notepad !!models.Software
    name: Notepad

general-settings:
  - !!models.GeneralSettings
    eula: "Käyttäjäehdot..."
    reviewDeadline: 14
