#!/bin/sh
#
# exam
#
# chkconfig: 345 80 10

APP_ROOT_PATH=/opt/exam/sitnet
APP_STAGING_PATH="$APP_ROOT_PATH/target/universal/stage"
APP_PATH="$APP_STAGING_PATH/bin/exam"
APP_OPTS="-DapplyEvolutions.default=true -Dapplication.secret=abcdefghijk"
APP_USER=sitnet
PID_FILE="$APP_STAGING_PATH/RUNNING_PID"

start()
{
    echo "Starting EXAM"
    sudo -u "$APP_USER" nohup "$APP_PATH" $APP_OPTS > /dev/null 2>&1 < /dev/null &
    sleep 3
    PID=`cat $PID_FILE`
    echo "DONE (PID=$PID)"
}

stop()
{
    echo "Stopping EXAM"
    sudo -u $APP_USER kill `cat $PID_FILE`
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
       stop
       start
       ;;
esac