#!/bin/sh
#
# /etc/init.d/exam
# 
# chkconfig: 35 90 10
# description: EXAM service daemon
#
# processname: exam

. /etc/init.d/functions

RETVAL=0
prog="exam"

APP_ROOT_PATH=/opt/exam/sitnet
APP_STAGING_PATH="${APP_ROOT_PATH}/target/universal/stage"
APP_PATH="${APP_STAGING_PATH}/bin/exam"
APP_USER=sitnet
PID_DIR="/var/run/${prog}"
LOG_DIR="/var/log/${prog}"
PID_FILE="${PID_DIR}/${prog}.pid"
APP_SECRET="46bsvqiOr2X^OptDMMhHTmWKjeCJH[0]J7F2i8JxPY[nhrK9gBs:J02Et[X[7"
APP_OPTS="-Dapplication.secret=${APP_SECRET} -DapplyEvolutions.default=true -Dpidfile.path=${PID_FILE}"

start()
{
    echo -n "Starting ${prog}:"
    mkdir -p ${PID_DIR} ${LOG_DIR}
    chown ${APP_USER}:${APP_USER} ${PID_DIR} ${LOG_DIR}
    su -l ${APP_USER} -c "nohup ${APP_PATH} ${APP_OPTS} > ${LOG_DIR}/${prog}.log 2>&1 < /dev/null" &
    i="0"
    while [ ${i} -lt 20 ]
    do
        if [ -f ${PID_FILE} ]
        then
            break
        fi
        sleep 1
        i=$[$i+1]
    done
    if [ -f ${PID_FILE} ]
    then
        RETVAL=0
        touch /var/lock/subsys/${prog}
        success
    else
        RETVAL=1
        failure
    fi
    echo
}

stop()
{
    echo -n "Stopping exam:"
    if [ -f ${PID_FILE} ]
    then
        su -l ${APP_USER} -c "kill `cat ${PID_FILE}`"
        rm -f /var/lock/subsys/${prog}
    fi
    RETVAL=0
    success
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status ${prog}
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        RETVAL=1
esac
exit ${RETVAL}
